services:
  app:
    image: atharva0418/springboot-gradle-app
    container_name: springboot-app
    ports:
      - 3000:3000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
