name: CI Pipeline

env:
  # Define any environment variables needed for your tests
  DB_URL: jdbc:mysql://127.0.0.1:3306/password_manager
  DB_USERNAME: root
  DB_PASSWORD: testrootpass
  DB_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      with:
        gradle-version: '8.9'

    - name: Run Gradle Build
      run: gradle build


