name: CI Pipeline

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: testrootpass
        ports:
          - 3306/3306
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '8.9'

    - name: Build with Gradle 8.9
      run: gradle build
      env:
        DATABASE_NAME: testdb
        DATABASE_USERNAME: root          
        DATABASE_PASSWORD: testrootpass          
        DATABASE_ENDPOINT: 127.0.0.1


