name: CI Pipeline

env:
  # Define any environment variables needed for your tests
  DB_URL: jdbc:mysql://127.0.0.1:3306/password_manager
  DB_USERNAME: root
  DB_PASSWORD: testrootpass

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      with:
        gradle-version: '8.9'

    - name: Run Gradle Build
      run: gradle build
    
    - name: Test Report
      uses: phoenix-actions/test-reporting@v8
      id: test-report               # Set ID reference for step
      if: success() || failure()    # run this step even if previous step failed
      with:
           name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results


